### ISSUE TITLE
[ROADMAP] 1.0

### ISSUE THREAD

**Issue by BlowaXD** [BlowaXD/SaltyEmu#17]
# Roadmap - 1.0 - Stable Release
This roadmap is given for the first stable release, it also include a basic gameplay with essential game features to enjoy spending some time to play

## Project Features :
 - [x]  Easy deployment (Docker compose is enough for development purposes)
 - [ ] Multiserver support & multi channels (Needs a rework)
 - [ ] Centralized Logging (Datadog, Cassandra)
 - [ ] Monitoring - Grafana

## Game Features : 
- [x] Movements
- [ ] Inventory
- [ ] Trades
- [x] Item given by packages
- [ ] Map
   - [x] Monsters
   - [x] NPCs
   - [x] Portals
- [ ] Shops
- [ ] Leveling
- [ ] Groups
- [ ] Friends & Blocked
- [ ] Families
- [x] Item Usage
- [x] Npc dialogs
- [ ] Battle
- [x] Drops
- [x] Skills
- [x] Basic AI
- [ ] Move to another channel (Special Channel (like act4..) transition)
- [ ] Chat
   - [x] General
   - [ ] Global chat
   - [x] Item linking
   - [ ] Hero Chat
